import { Amplify } from "aws-amplify";
import outputs from "../../amplify_outputs.json";

/**
 * Configure Amplify for client-side usage.
 * The amplify_outputs.json is generated by `npx ampx sandbox` or deployment.
 */
let configured = false;

export function configureAmplify() {
  if (configured) return;
  
  try {
    Amplify.configure(outputs, { ssr: true });
    configured = true;
  } catch (error) {
    console.warn("Failed to configure Amplify:", error);
  }
}

export function isAmplifyConfigured() {
  return configured;
}
